services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=maxim
      - POSTGRES_USER=maxim
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    restart: unless-stopped

  django_app:
    container_name: django_app
    image: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app/
    ports:
      - '8000:8000'
    env_file:
      - ./env/django.env
    depends_on:
      - postgres


  gunicorn:
    container_name: gunicorn_server
    build: .
    command: gunicorn --config gunicorn/gunicorn.conf.py AskPupkin_Makarenkov.wsgi
    env_file:
      - ./env/django.env
    volumes:
      - .:/opt/app/
    ports:
      - '8081:8081'
    depends_on:
      - django_app

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/static:ro
      - ./nginx/logs:/var/log/nginx
      - ./uploads:/usr/share/uploads:ro
    restart: unless-stopped


